services:
  postgres:
    image: postgres:13
    env_file:
      - airflow.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - default

  airflow-init:
    build:
      context: /Users/atharvnanaware/Desktop/Project/Data_Main/Reddit Data Pipeline Engineering
      dockerfile: Dockerfile
    image: custom-airflow:2.10.3-python3.10
    env_file:
      - airflow.env
    command: >
      bash -c "pip install -r /opt/airflow/requirements.txt && airflow db init && airflow db upgrade && airflow users create --username admin --firstname admin --lastname admin --role Admin --email airflow@airflow.com --password admin"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./config:/opt/airflow/config
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./etls:/opt/airflow/etls
      - ./logs:/opt/airflow/logs
      - ./pipelines:/opt/airflow/pipelines
      - ./plugins:/opt/airflow/plugins
      - ./tests:/opt/airflow/tests
      - ./utils:/opt/airflow/utils
      - ./requirements.txt:/opt/airflow/requirements.txt
    networks:
      - default

  airflow-webserver:
    build:
      context: /Users/atharvnanaware/Desktop/Project/Data_Main/Reddit Data Pipeline Engineering
      dockerfile: Dockerfile
    image: custom-airflow:2.10.3-python3.10
    env_file:
      - airflow.env
    command: webserver
    depends_on:
      - airflow-init
    ports:
      - "8080:8080"
    volumes:
      - ./config:/opt/airflow/config
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./etls:/opt/airflow/etls
      - ./logs:/opt/airflow/logs
      - ./pipelines:/opt/airflow/pipelines
      - ./plugins:/opt/airflow/plugins
      - ./tests:/opt/airflow/tests
      - ./utils:/opt/airflow/utils
      - ./requirements.txt:/opt/airflow/requirements.txt
    networks:
      - default

  airflow-scheduler:
    build:
      context: /Users/atharvnanaware/Desktop/Project/Data_Main/Reddit Data Pipeline Engineering
      dockerfile: Dockerfile
    image: custom-airflow:2.10.3-python3.10
    env_file:
      - airflow.env
    command: scheduler
    depends_on:
      - airflow-init
    volumes:
      - ./config:/opt/airflow/config
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./etls:/opt/airflow/etls
      - ./logs:/opt/airflow/logs
      - ./pipelines:/opt/airflow/pipelines
      - ./plugins:/opt/airflow/plugins
      - ./tests:/opt/airflow/tests
      - ./utils:/opt/airflow/utils
      - ./requirements.txt:/opt/airflow/requirements.txt
    networks:
      - default

  airflow-worker:
    build:
      context: /Users/atharvnanaware/Desktop/Project/Data_Main/Reddit Data Pipeline Engineering
      dockerfile: Dockerfile
    image: custom-airflow:2.10.3-python3.10
    env_file:
      - airflow.env
    command: celery worker
    depends_on:
      - airflow-init
      - postgres
      - redis
    volumes:
      - ./config:/opt/airflow/config
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./etls:/opt/airflow/etls
      - ./logs:/opt/airflow/logs
      - ./pipelines:/opt/airflow/pipelines
      - ./plugins:/opt/airflow/plugins
      - ./tests:/opt/airflow/tests
      - ./utils:/opt/airflow/utils
      - ./requirements.txt:/opt/airflow/requirements.txt
    networks:
      - default

volumes:
  postgres_data:
    name: redditdatapipelineengineering_postgres_data
  redis_data:
    name: redditdatapipelineengineering_redis_data

networks:
  default:
    name: redditdatapipelineengineering_default
